name: Draft of Cypress Tests Workflow - must be updated

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=https://fakestore.testelka.pl/
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notification
        if: always() 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: 'test-notifications'
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          SLACK_ICON: https://github.com/cypress-io.png?size=48
          SLACK_MESSAGE: "Testy Cypress na ${{ github.repository }} zakończone statusem: ${{ job.status }}"
          SLACK_TITLE: "Cypress Test Results"
          SLACK_USERNAME: CypressBot